import { Box } from '@mantine/core';
import type { NextPage } from 'next';
import Image from 'next/image';
import { Navigation } from '../components/Navigation';
import { PageHead } from '../components/PageHead';
import { DefaultLayout } from '../layouts';
import styles from '../styles/Home.module.css';

const Home: NextPage = () => {
  return (
    <>
      <PageHead
        title="Create Next App"
        description="Generated by create next app"
      />
      <Box className={styles.container}>
        <DefaultLayout>
          <Navigation />
        </DefaultLayout>
      </Box>
    </>
  );
};

export default Home;
