import { NextPage } from 'next';
import { Box } from '../../components/Box';
import { Head } from '../../components/Head';
import { Navigation } from '../../components/Navigation';
import { DefaultLayout } from '../../layouts';

const HelloWorld: NextPage = () => {
  return (
    <Box>
      <Head
        title="Hello world"
        description="Generated by create next app"
      />
      <DefaultLayout>
        <Navigation />
      </DefaultLayout>
    </Box>
  );
};

export default HelloWorld;
