import { NextPage } from 'next';
import { PageHead } from '../../components/PageHead';
import { Navigation } from '../../components/Navigation';
import { DefaultLayout } from '../../layouts';
import { Box } from '@mantine/core';

const HelloWorld: NextPage = () => {
  return (
    <Box>
      <PageHead
        title="Hello world"
        description="Generated by create next app"
      />
      <DefaultLayout>
        <Navigation/>
      </DefaultLayout>
    </Box>
  );
};

export default HelloWorld;
